### ISSUE TITLE
Xabu danado: o readme precisa de mais detalhes!

### ISSUE THREAD

**Issue by brunoc-dev** [wise-man-distracted/projeto-x#1]
- [ ] informações de instalação do projeto
- [ ] informações de contribuição

**Comment by wise-man-distracted** [comment]
Estamos olhando isso e nossa equipe de MarkDown já está tentando resolver.
Você tem alguma sugestão do que fazer?

**Comment by brunoc-dev** [comment]
Incluir comandos do terminal para clonar e rodar o projeto.

**Comment by wise-man-distracted** [comment]
`git clone`
`npm i`
Colocarei no README já
